version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company-db
      MYSQL_USER: promotion-api
      MYSQL_PASSWORD: 123456
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    hostname: my-rabbit
volumes:
    db_data:
